Blast:
  hitlist_size: 5000
  blast_database: refseq_protein
  blast_local: False
  pro_blast_: False
  length_restrict: False
  length_margin: 0.5
  max_low_identity_seqs: 1
  min_low_identity_seqs: 1
  expected_min_identity: 0.25
  additional_hits: 2000

Clustering:
  cluster_seqs: False
  similarity: 0.6
  pro_clustering_: False
  similarity_step: 0.02
  min_number_of_clusters_to_cluster_again: 50
  max_number_of_clusters_to_cluster_again: 300

Pfam domains:
  check_pfam_domains: False

Alignment:
  align_seqs: False
  trim: False

Weblogo:
  generate_logo: False
  weblogo_format: png

Tree:
  generate_tree: False
  tree_type: NJ
  bootstrap_replications: 100

Outputs:
  outputs_dir: outputs
